__version__ = "0.1.5"
from argParseFromDoc.autoArgparseFunction import get_parser_from_function
from argParseFromDoc.AutoArgumentParser import AutoArgumentParser, parse_function_and_call
from argParseFromDoc.commandStrGenerator import generate_command_for_argparseFromDoc